# https://www.data.gouv.fr/fr/datasets/lieux-de-vaccination-contre-la-grippe-pharmacies-sante-fr/

In [1]:
import pandas as pd

df = pd.read_csv(r'https://www.data.gouv.fr/fr/datasets/r/479afe3e-a2aa-4519-b509-ba9c106a5576', sep=';')
df

,Finess,Titre,Adresse_voie 1,Adresse_voie 2,Adresse_codepostal,Adresse_ville,Modalites_accueil,Adresse_latitude,Adresse_longitude
0,750020927,Pharmacie Dang Trung,237 Rue de Charenton,NaN,75012,Paris,NaN,48.837516,2.391121
1,750032955,Pharmacie Lemaitre - Lacroix,141 Rue Marcadet,NaN,75018,Paris,NaN,48.891153,2.340128
2,910007533,Pharmacie Du Relais,40 Rue CHARLES MORY - AVENUE DE L’EUR,NaN,91210,Draveil,NaN,48.677829,2.411785
3,750015760,Pharmacie Caumartin,24 Rue de Caumartin,NaN,75009,Paris,NaN,48.871864,2.328260
4,750022352,Pharmacie Serafim,37 Boulevard Arago,NaN,75013,Paris,NaN,48.835229,2.347606
...,...,...,...,...,...,...,...,...,...
2467,850014721,Pharmacie Du Grand Palais,20 Rue de Nantes,NaN,85300,Challans,<h3>Informations complémentaires relatives à l...,46.850878,-1.875416
2468,720009091,Pharmacie Ferran - Devaux,182 Avenue Olivier Heuzé,NaN,72000,Le Mans,NaN,47.993177,0.174714
2469,520001173,Pharmacie Du Cavalier,48 Avenue de la République,NaN,52000,Chaumont,NaN,48.100119,5.144791
2470,240011320,Pharmacie Chapard,36 Rue Gambetta,NaN,24000,Périgueux,NaN,45.186417,0.716403
2471,770004315,Pharmacie Bodeau,28 Route de Paris,NaN,77930,Chailly-en-Bière,NaN,48.467446,2.606152

In [2]:
df[['Adresse_latitude', 'Adresse_longitude']].isna().sum()

Adresse_latitude     9
Adresse_longitude    9
dtype: int64

In [3]:
df = df.dropna(subset=['Adresse_latitude','Adresse_longitude'])

In [4]:
df

,Finess,Titre,Adresse_voie 1,Adresse_voie 2,Adresse_codepostal,Adresse_ville,Modalites_accueil,Adresse_latitude,Adresse_longitude
0,750020927,Pharmacie Dang Trung,237 Rue de Charenton,NaN,75012,Paris,NaN,48.837516,2.391121
1,750032955,Pharmacie Lemaitre - Lacroix,141 Rue Marcadet,NaN,75018,Paris,NaN,48.891153,2.340128
2,910007533,Pharmacie Du Relais,40 Rue CHARLES MORY - AVENUE DE L’EUR,NaN,91210,Draveil,NaN,48.677829,2.411785
3,750015760,Pharmacie Caumartin,24 Rue de Caumartin,NaN,75009,Paris,NaN,48.871864,2.328260
4,750022352,Pharmacie Serafim,37 Boulevard Arago,NaN,75013,Paris,NaN,48.835229,2.347606
...,...,...,...,...,...,...,...,...,...
2467,850014721,Pharmacie Du Grand Palais,20 Rue de Nantes,NaN,85300,Challans,<h3>Informations complémentaires relatives à l...,46.850878,-1.875416
2468,720009091,Pharmacie Ferran - Devaux,182 Avenue Olivier Heuzé,NaN,72000,Le Mans,NaN,47.993177,0.174714
2469,520001173,Pharmacie Du Cavalier,48 Avenue de la République,NaN,52000,Chaumont,NaN,48.100119,5.144791
2470,240011320,Pharmacie Chapard,36 Rue Gambetta,NaN,24000,Périgueux,NaN,45.186417,0.716403
2471,770004315,Pharmacie Bodeau,28 Route de Paris,NaN,77930,Chailly-en-Bière,NaN,48.467446,2.606152

In [5]:
import geopy
from geopy.geocoders import BANFrance

In [6]:
locator = BANFrance(user_agent="test")

coordinates = "48.837516, 2.391121"
location = locator.reverse(coordinates)
location.raw['properties']['context'].split(',')[2]

' Île-de-France'

In [28]:
locator = BANFrance(user_agent="test")

coordinates = "15.881647, -61.314753"
location = locator.reverse(coordinates)
location.raw['properties']['context'].split(',')[1]

' Guadeloupe'

In [33]:
len(location.raw['properties']['context'].split(','))

2

In [34]:
def get_region(lat, lon):
    locator = BANFrance(user_agent="test")
    coordinates = str(lat) + ',' + str(lon)
    location = locator.reverse(coordinates)
    
    if len(location.raw['properties']['context'].split(',')) == 3:
        return location.raw['properties']['context'].split(',')[2]
    
    if len(location.raw['properties']['context'].split(',')) == 2:
        return location.raw['properties']['context'].split(',')[1]
    
    else:
        return

In [10]:
df.reset_index(inplace=True)

In [35]:
df['region'] = " "

<ipython-input-35-b63278b740d9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['region'] = " "

In [36]:
for k in range(len(df)):
    if df['region'][k] == " ":
        df['region'][k] = get_region(df['Adresse_latitude'][k], df['Adresse_longitude'][k])
    else:
        pass

<ipython-input-36-a39b94466c4a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['region'][k] = get_region(df['Adresse_latitude'][k], df['Adresse_longitude'][k])
D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3437: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [52]:
df['region']

0             Île-de-France
1             Île-de-France
2             Île-de-France
3             Île-de-France
4             Île-de-France
               ...
2458       Pays de la Loire
2459       Pays de la Loire
2460              Grand Est
2461     Nouvelle-Aquitaine
2462          Île-de-France
Name: region, Length: 2463, dtype: object

In [51]:
df.to_csv('App/flu_vaccination.csv', encoding='utf-8')

# https://www.sentiweb.fr/france/fr/?page=table

In [6]:
import pandas as pd

df2 = pd.read_csv(r'https://www.sentiweb.fr/datasets/incidence-PAY-3.csv', sep =',',skiprows = 1, encoding = 'iso-8859-1')
df2

,week,indicator,inc,inc_low,inc_up,inc100,inc100_low,inc100_up,geo_insee,geo_name
0,202252,3,189739,172229.0,207249.0,286,260.0,312.0,FR,France
1,202251,3,255228,238612.0,271844.0,385,360.0,410.0,FR,France
2,202250,3,234279,219533.0,249025.0,353,331.0,375.0,FR,France
3,202249,3,163421,151727.0,175115.0,246,228.0,264.0,FR,France
4,202248,3,121884,111932.0,131836.0,184,169.0,199.0,FR,France
...,...,...,...,...,...,...,...,...,...,...
1987,198448,3,78620,60634.0,96606.0,143,110.0,176.0,FR,France
1988,198447,3,72029,54274.0,89784.0,131,99.0,163.0,FR,France
1989,198446,3,87330,67686.0,106974.0,159,123.0,195.0,FR,France
1990,198445,3,135223,101414.0,169032.0,246,184.0,308.0,FR,France
1991,198444,3,68422,20056.0,116788.0,125,37.0,213.0,FR,France

In [7]:
df2 = df2.sort_values(by = ['week'])
df2.reset_index(inplace=True)
df2

,index,week,indicator,inc,inc_low,inc_up,inc100,inc100_low,inc100_up,geo_insee,geo_name
0,1991,198444,3,68422,20056.0,116788.0,125,37.0,213.0,FR,France
1,1990,198445,3,135223,101414.0,169032.0,246,184.0,308.0,FR,France
2,1989,198446,3,87330,67686.0,106974.0,159,123.0,195.0,FR,France
3,1988,198447,3,72029,54274.0,89784.0,131,99.0,163.0,FR,France
4,1987,198448,3,78620,60634.0,96606.0,143,110.0,176.0,FR,France
...,...,...,...,...,...,...,...,...,...,...,...
1987,4,202248,3,121884,111932.0,131836.0,184,169.0,199.0,FR,France
1988,3,202249,3,163421,151727.0,175115.0,246,228.0,264.0,FR,France
1989,2,202250,3,234279,219533.0,249025.0,353,331.0,375.0,FR,France
1990,1,202251,3,255228,238612.0,271844.0,385,360.0,410.0,FR,France
1991,0,202252,3,189739,172229.0,207249.0,286,260.0,312.0,FR,France

In [8]:
str(df2['week'][0])[4:6]

'44'

In [9]:
def get_year(week): 
    return str(week)[:4]

df2['year'] = df2['week'].map(get_year)

In [10]:
def get_nweek(week): 
    return str(week)[4:6]

df2['nweek'] = df2['week'].map(get_nweek)

In [11]:
df2['week2'] = df2['week'].map(get_year) + ' - week '+ df2['week'].map(get_nweek)

In [12]:
df2.head(50)

,index,week,indicator,inc,inc_low,inc_up,inc100,inc100_low,inc100_up,geo_insee,geo_name,year,nweek,week2
0,1991,198444,3,68422,20056.0,116788.0,125,37.0,213.0,FR,France,1984,44,1984 - week 44
1,1990,198445,3,135223,101414.0,169032.0,246,184.0,308.0,FR,France,1984,45,1984 - week 45
2,1989,198446,3,87330,67686.0,106974.0,159,123.0,195.0,FR,France,1984,46,1984 - week 46
3,1988,198447,3,72029,54274.0,89784.0,131,99.0,163.0,FR,France,1984,47,1984 - week 47
4,1987,198448,3,78620,60634.0,96606.0,143,110.0,176.0,FR,France,1984,48,1984 - week 48
5,1986,198449,3,101073,81684.0,120462.0,184,149.0,219.0,FR,France,1984,49,1984 - week 49
6,1985,198450,3,123680,101401.0,145959.0,225,184.0,266.0,FR,France,1984,50,1984 - week 50
7,1984,198451,3,101726,80242.0,123210.0,185,146.0,224.0,FR,France,1984,51,1984 - week 51
8,1983,198452,3,84830,60602.0,109058.0,154,110.0,198.0,FR,France,1984,52,1984 - week 52
9,1982,198501,3,85489,65918.0,105060.0,155,120.0,190.0,FR,France,1985,01,1985 - week 01
10,1981,198502,3,97586,80949.0,114223.0,177,147.0,207.0,FR,France,1985,02,1985 - week 02
11,1980,198503,3,213901,174689.0,253113.0,388,317.0,459.0,FR,France,1985,03,1985 - week 03
12,1979,198504,3,424937,390794.0,459080.0,770,708.0,832.0,FR,France,1985,04,1985 - week 04
13,1978,198505,3,637302,592795.0,681809.0,1155,1074.0,1236.0,FR,France,1985,05,1985 - week 05
14,1977,198506,3,565825,518011.0,613639.0,1026,939.0,1113.0,FR,France,1985,06,1985 - week 06
15,1976,198507,3,471852,432599.0,511105.0,855,784.0,926.0,FR,France,1985,07,1985 - week 07
16,1975,198508,3,389886,359529.0,420243.0,707,652.0,762.0,FR,France,1985,08,1985 - week 08
17,1974,198509,3,369895,341109.0,398681.0,670,618.0,722.0,FR,France,1985,09,1985 - week 09
18,1973,198510,3,353231,326279.0,380183.0,640,591.0,689.0,FR,France,1985,10,1985 - week 10
19,1972,198511,3,276205,252399.0,300011.0,501,458.0,544.0,FR,France,1985,11,1985 - week 11
20,1971,198512,3,245240,223304.0,267176.0,445,405.0,485.0,FR,France,1985,12,1985 - week 12
21,1970,198513,3,197206,176080.0,218332.0,357,319.0,395.0,FR,France,1985,13,1985 - week 13
22,1969,198514,3,134545,114400.0,154690.0,244,207.0,281.0,FR,France,1985,14,1985 - week 14
23,1968,198515,3,63881,45538.0,82224.0,116,83.0,149.0,FR,France,1985,15,1985 - week 15
24,1967,198516,3,50362,36451.0,64273.0,91,66.0,116.0,FR,France,1985,16,1985 - week 16
25,1966,198517,3,34053,24366.0,43740.0,62,44.0,80.0,FR,France,1985,17,1985 - week 17
26,1965,198518,3,40555,29935.0,51175.0,74,55.0,93.0,FR,France,1985,18,1985 - week 18
27,1964,198519,3,43154,32821.0,53487.0,78,59.0,97.0,FR,France,1985,19,1985 - week 19
28,1963,198520,3,27896,20885.0,34907.0,51,38.0,64.0,FR,France,1985,20,1985 - week 20
29,1962,198521,3,26096,19621.0,32571.0,47,35.0,59.0,FR,France,1985,21,1985 - week 21
30,1961,198522,3,24099,17190.0,31008.0,44,31.0,57.0,FR,France,1985,22,1985 - week 22
31,1960,198523,3,19373,10010.0,28736.0,35,18.0,52.0,FR,France,1985,23,1985 - week 23
32,1959,198524,3,19855,13577.0,26133.0,36,25.0,47.0,FR,France,1985,24,1985 - week 24
33,1958,198525,3,19362,12454.0,26270.0,35,22.0,48.0,FR,France,1985,25,1985 - week 25
34,1957,198526,3,18609,12637.0,24581.0,34,23.0,45.0,FR,France,1985,26,1985 - week 26
35,1956,198527,3,19670,11761.0,27579.0,36,22.0,50.0,FR,France,1985,27,1985 - week 27
36,1955,198528,3,14588,7659.0,21517.0,26,13.0,39.0,FR,France,1985,28,1985 - week 28
37,1954,198529,3,13054,6474.0,19634.0,24,12.0,36.0,FR,France,1985,29,1985 - week 29
38,1953,198530,3,11598,5507.0,17689.0,21,10.0,32.0,FR,France,1985,30,1985 - week 30
39,1952,198531,3,16958,8479.0,25437.0,31,16.0,46.0,FR,France,1985,31,1985 - week 31
40,1951,198532,3,7488,1851.0,13125.0,14,4.0,24.0,FR,France,1985,32,1985 - week 32
41,1950,198533,3,22611,8819.0,36403.0,41,16.0,66.0,FR,France,1985,33,1985 - week 33
42,1949,198534,3,40389,24786.0,55992.0,73,45.0,101.0,FR,France,1985,34,1985 - week 34
43,1948,198535,3,30215,18546.0,41884.0,55,34.0,76.0,FR,France,1985,35,1985 - week 35
44,1947,198536,3,27986,18992.0,36980.0,51,35.0,67.0,FR,France,1985,36,1985 - week 36
45,1946,198537,3,22219,15626.0,28812.0,40,28.0,52.0,FR,France,1985,37,1985 - week 37
46,1945,198538,3,27605,20614.0,34596.0,50,37.0,63.0,FR,France,1985,38,1985 - week 38
47,1944,198539,3,39819,31234.0,48404.0,72,56.0,88.0,FR,France,1985,39,1985 - week 39
48,1943,198540,3,49739,40335.0,59143.0,90,73.0,107.0,FR,France,1985,40,1985 - week 40
49,1942,198541,3,45712,36755.0,54669.0,83,67.0,99.0,FR,France,1985,41,1985 - week 41

In [13]:
df2.tail(50)

,index,week,indicator,inc,inc_low,inc_up,inc100,inc100_low,inc100_up,geo_insee,geo_name,year,nweek,week2
1942,49,202203,3,67412,60291.0,74533.0,102,91.0,113.0,FR,France,2022,03,2022 - week 03
1943,48,202204,3,66266,59163.0,73369.0,100,89.0,111.0,FR,France,2022,04,2022 - week 04
1944,47,202205,3,60757,53958.0,67556.0,92,82.0,102.0,FR,France,2022,05,2022 - week 05
1945,46,202206,3,42557,36599.0,48515.0,64,55.0,73.0,FR,France,2022,06,2022 - week 06
1946,45,202207,3,31636,26432.0,36840.0,48,40.0,56.0,FR,France,2022,07,2022 - week 07
1947,44,202208,3,28034,23245.0,32823.0,42,35.0,49.0,FR,France,2022,08,2022 - week 08
1948,43,202209,3,43750,37938.0,49562.0,66,57.0,75.0,FR,France,2022,09,2022 - week 09
1949,42,202210,3,80177,72368.0,87986.0,121,109.0,133.0,FR,France,2022,10,2022 - week 10
1950,41,202211,3,113273,104095.0,122451.0,171,157.0,185.0,FR,France,2022,11,2022 - week 11
1951,40,202212,3,159809,148839.0,170779.0,241,224.0,258.0,FR,France,2022,12,2022 - week 12
1952,39,202213,3,187355,175153.0,199557.0,283,265.0,301.0,FR,France,2022,13,2022 - week 13
1953,38,202214,3,159637,147889.0,171385.0,241,223.0,259.0,FR,France,2022,14,2022 - week 14
1954,37,202215,3,106385,96079.0,116691.0,160,144.0,176.0,FR,France,2022,15,2022 - week 15
1955,36,202216,3,54405,46976.0,61834.0,82,71.0,93.0,FR,France,2022,16,2022 - week 16
1956,35,202217,3,35950,30255.0,41645.0,54,45.0,63.0,FR,France,2022,17,2022 - week 17
1957,34,202218,3,27569,22584.0,32554.0,42,34.0,50.0,FR,France,2022,18,2022 - week 18
1958,33,202219,3,17178,13462.0,20894.0,26,20.0,32.0,FR,France,2022,19,2022 - week 19
1959,32,202220,3,17355,13600.0,21110.0,26,20.0,32.0,FR,France,2022,20,2022 - week 20
1960,31,202221,3,11804,8686.0,14922.0,18,13.0,23.0,FR,France,2022,21,2022 - week 21
1961,30,202222,3,14239,10930.0,17548.0,21,16.0,26.0,FR,France,2022,22,2022 - week 22
1962,29,202223,3,17159,13450.0,20868.0,26,20.0,32.0,FR,France,2022,23,2022 - week 23
1963,28,202224,3,19294,15406.0,23182.0,29,23.0,35.0,FR,France,2022,24,2022 - week 24
1964,27,202225,3,22887,18582.0,27192.0,35,29.0,41.0,FR,France,2022,25,2022 - week 25
1965,26,202226,3,29421,24314.0,34528.0,44,36.0,52.0,FR,France,2022,26,2022 - week 26
1966,25,202227,3,36015,29709.0,42321.0,54,44.0,64.0,FR,France,2022,27,2022 - week 27
1967,24,202228,3,23387,17970.0,28804.0,35,27.0,43.0,FR,France,2022,28,2022 - week 28
1968,23,202229,3,20801,15829.0,25773.0,31,24.0,38.0,FR,France,2022,29,2022 - week 29
1969,22,202230,3,15006,10738.0,19274.0,23,17.0,29.0,FR,France,2022,30,2022 - week 30
1970,21,202231,3,13257,8905.0,17609.0,20,13.0,27.0,FR,France,2022,31,2022 - week 31
1971,20,202232,3,12222,7749.0,16695.0,18,11.0,25.0,FR,France,2022,32,2022 - week 32
1972,19,202233,3,7586,4442.0,10730.0,11,6.0,16.0,FR,France,2022,33,2022 - week 33
1973,18,202234,3,7498,4731.0,10265.0,11,7.0,15.0,FR,France,2022,34,2022 - week 34
1974,17,202235,3,9283,6485.0,12081.0,14,10.0,18.0,FR,France,2022,35,2022 - week 35
1975,16,202236,3,14120,10487.0,17753.0,21,16.0,26.0,FR,France,2022,36,2022 - week 36
1976,15,202237,3,21395,17076.0,25714.0,32,25.0,39.0,FR,France,2022,37,2022 - week 37
1977,14,202238,3,28781,23733.0,33829.0,43,35.0,51.0,FR,France,2022,38,2022 - week 38
1978,13,202239,3,39902,34168.0,45636.0,60,51.0,69.0,FR,France,2022,39,2022 - week 39
1979,12,202240,3,41927,36115.0,47739.0,63,54.0,72.0,FR,France,2022,40,2022 - week 40
1980,11,202241,3,48583,42388.0,54778.0,73,64.0,82.0,FR,France,2022,41,2022 - week 41
1981,10,202242,3,47462,40773.0,54151.0,72,62.0,82.0,FR,France,2022,42,2022 - week 42
1982,9,202243,3,44769,36884.0,52654.0,68,56.0,80.0,FR,France,2022,43,2022 - week 43
1983,8,202244,3,34713,28880.0,40546.0,52,43.0,61.0,FR,France,2022,44,2022 - week 44
1984,7,202245,3,45306,38909.0,51703.0,68,58.0,78.0,FR,France,2022,45,2022 - week 45
1985,6,202246,3,67735,60075.0,75395.0,102,90.0,114.0,FR,France,2022,46,2022 - week 46
1986,5,202247,3,96447,87259.0,105635.0,145,131.0,159.0,FR,France,2022,47,2022 - week 47
1987,4,202248,3,121884,111932.0,131836.0,184,169.0,199.0,FR,France,2022,48,2022 - week 48
1988,3,202249,3,163421,151727.0,175115.0,246,228.0,264.0,FR,France,2022,49,2022 - week 49
1989,2,202250,3,234279,219533.0,249025.0,353,331.0,375.0,FR,France,2022,50,2022 - week 50
1990,1,202251,3,255228,238612.0,271844.0,385,360.0,410.0,FR,France,2022,51,2022 - week 51
1991,0,202252,3,189739,172229.0,207249.0,286,260.0,312.0,FR,France,2022,52,2022 - week 52

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/EM_of_influenza_virus.jpg/260px-EM_of_influenza_virus.jpg)

In [17]:
df2

,index,week,indicator,inc,inc_low,inc_up,inc100,inc100_low,inc100_up,geo_insee,geo_name,year,nweek,week2
0,1991,198444,3,68422,20056.0,116788.0,125,37.0,213.0,FR,France,1984,44,1984 - week 44
1,1990,198445,3,135223,101414.0,169032.0,246,184.0,308.0,FR,France,1984,45,1984 - week 45
2,1989,198446,3,87330,67686.0,106974.0,159,123.0,195.0,FR,France,1984,46,1984 - week 46
3,1988,198447,3,72029,54274.0,89784.0,131,99.0,163.0,FR,France,1984,47,1984 - week 47
4,1987,198448,3,78620,60634.0,96606.0,143,110.0,176.0,FR,France,1984,48,1984 - week 48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,4,202248,3,121884,111932.0,131836.0,184,169.0,199.0,FR,France,2022,48,2022 - week 48
1988,3,202249,3,163421,151727.0,175115.0,246,228.0,264.0,FR,France,2022,49,2022 - week 49
1989,2,202250,3,234279,219533.0,249025.0,353,331.0,375.0,FR,France,2022,50,2022 - week 50
1990,1,202251,3,255228,238612.0,271844.0,385,360.0,410.0,FR,France,2022,51,2022 - week 51
1991,0,202252,3,189739,172229.0,207249.0,286,260.0,312.0,FR,France,2022,52,2022 - week 52

In [20]:
df2.groupby(['nweek']).sum()['inc']

nweek
01    4930784
02    4834987
03    5759284
04    7203950
05    8398787
06    8676040
07    7531588
08    5981823
09    4505731
10    3665436
11    3123160
12    2751105
13    2389179
14    1937747
15    1251689
16     878340
17     599116
18     404172
19     340301
20     297580
21     244908
22     236038
23     267007
24     244838
25     240784
26     215359
27     207708
28     166684
29     171088
30     145534
31     208765
32     145307
33     167609
34     192846
35     199013
36     247144
37     404484
38     614313
39     793614
40     849854
41     912309
42     960993
43     973842
44     996385
45    1165639
46    1411244
47    2384254
48    3839160
49    5543397
50    6619566
51    7105721
52    5575492
53     387775
Name: inc, dtype: int64